# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/kosmoshub
spring.datasource.username=postgres
spring.datasource.password=ra3z^TJ5:0&P
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Pool de Conexões (HikariCP)
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
spring.jpa.open-in-view=false

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Use 'update' APENAS em desenvolvimento local. Em Produção, use 'validate' + Flyway
spring.jpa.hibernate.ddl-auto=validate

# Exibição de SQL (Aviso: Em produção, mude ambos para FALSE para não destruir a performance de I/O)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SEGURANÇA / JWT
# ==========================================
jwt.secret=${JWT_SECRET}