# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/kosmoshub
spring.datasource.username=postgres
spring.datasource.password=ra3z^TJ5:0&P
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# Exibe os comandos SQL no terminal para acompanharmos a mágica
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# A Magia: Cria as tabelas automaticamente baseado no Java
spring.jpa.hibernate.ddl-auto=update

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect